config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
    
  resources :projects
  resources :tasks
  
  get 'timesheet_report' => 'tasks#timesheet_report', as: 'timesheet_report'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  
  belongs_to :user
  has_many :tasks, dependent: :destroy
   
  validates :name, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
  
  belongs_to :user
  belongs_to :project
  
  scope :under_project, -> (project_id) { where("project_id = ?", project_id) }
  
  validates :name, :time_taken, :date, :presence => true
  validates :time_taken, :numericality => { greater_than_or_equal_to: 0, less_than: 24 }

  def find_proj_name(id)
    Project.find_by_id(id).name
  end
  
  def self.find_user_tasks(tasks, id)  
    id.blank? ? tasks : tasks.under_project(id.to_i)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :projects
  has_many :tasks
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    before_action :authenticate_user!
    
    require 'will_paginate/array'
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :find_user_tasks, only: [:index]
  
  def index
    @tasks = Task.find_user_tasks(@tasks, params[:project_id])
  end
  
  private 
  
  def find_user_tasks
    @tasks = current_user.try(:tasks)
  end  
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :find_project, only: [:edit,:update,:destroy]
  
  def index
    @projects = Project.all
  end
  
  def new
    @project = Project.new
  end
  
  def edit
    
  end
  
  def create
    @project = Project.new(project_params.merge(:user_id => current_user.id))
    if @project.save
      flash[:success] = "Successfully Created Project"
      redirect_to projects_path
    else
      flash[:error] = @project.errors.full_messages.uniq.join(', ')
      redirect_to new_project_path
    end
  end
  
  def update
    proj = @project.update_attributes(project_params)
    if proj
      flash[:success] = "Successfully Updated Project"
      redirect_to projects_path
    else
      flash[:error] = @project.errors.full_messages.uniq.join(', ')
      redirect_to edit_project_path
    end
  end
  
  def destroy
    delete_proj = @project.destroy
    flash[:success] = "Successfully Deleted Project" if delete_proj
    flash[:error] = @project.errors.full_messages.uniq.join(', ') if !delete_proj
    redirect_to projects_path
  end
  
  private
    
  def project_params
    params.require(:project).permit(:name,:description,:user_id)
  end
  
  def find_project
    @project = Project.find_by_id(params[:id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :find_project, only: [:index,:new]
  before_action :find_task, only: [:edit,:update,:destroy]
  
  def index
    @tasks = @project.tasks
    respond_to do |format|
      format.html {@tasks = @tasks.paginate(:page => params[:page], :per_page => 2)}
      format.xlsx {render :xlsx => "index", :filename =>"timesheet_report_#{current_user.email}"}
    end  
  end
  
  def new
    @task = Task.new
  end
  
  def edit
    @project = Project.find_by_id(@task.project_id)
  end
  
  def create
    @task = Task.new(task_params.merge(:user_id => current_user.id))
    if @task.save
      flash[:success] = "Successfully Created Task"
      redirect_to tasks_path(project_id: @task.project_id)
    else
      flash[:error] = @task.errors.full_messages.uniq.join(', ')
      redirect_to new_task_path(project_id: @task.project_id)
    end
  end
  
  def update
    task = @task.update_attributes(task_params)
    if task
      flash[:success] = "Successfully Updated Task"
      redirect_to tasks_path(project_id: @task.project_id)
    else
      flash[:error] = @task.errors.full_messages.uniq.join(', ')
      redirect_to edit_task_path(project_id: @task.project_id)
    end
  end
  
  def destroy
    delete_task = @task.delete
    flash[:success] = "Successfully Deleted Task" if delete_task
    flash[:error] = @task.errors.full_messages.uniq.join(', ') if !delete_task
    redirect_to tasks_path(project_id: @task.project_id)
  end
  
  private
    
  def task_params
    params.require(:task).permit(:name,:description,:user_id,:project_id,:time_taken,:date)
  end
  
  def find_project
    @project = Project.find_by_id(params[:project_id])
  end  
  
  def find_task
    @task = Task.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_home_tasks_list.html.erb
<%if !@tasks.blank?%>
	<table class="table table-bordered table-striped table-condensed cf">
		<thead class="cf">
		  <tr style="width:100%;">
			<th>Project Name</th>
			<th>Task Id</th>
			<th>Assigned for</th>
			<th>Task Name</th>
			<th>Task Description</th>
			<th>Time Taken(in hours)</th>
			<th>Date</th>
		  </tr>
		</thead>
	    <tbody>
	        <%@tasks.each_with_index do |task| %>
	        <tr>
	        	<td>
	        	  <%=task.find_proj_name(task.project_id) if !task.project_id.blank?%>	
				</td>
				<td>
				  <%=task.id%>
				</td>
				<td>
				  <%=current_user.email%>
				</td>
				<td>
				  <%=task.name%>
				</td>
				<td>
					<%=task.description%>
				</td>
				<td>
				   <%=task.time_taken%>
				</td>
				<td>
				   <%=task.date.strftime("%m-%d-%Y") if task.date%>
				</td>	
	        </tr>
	        <%end %>
	    </tbody>
	</table>
<%else%>
	<div class="noRecords"><span class="fa fa-info-circle"></span> No Tasks Found</div>
<%end%>	

app/views/home/index.html.erb
<div class="breadcrumbs breadcrumb_style">
	<span class="fa fa-home"></span> /<span class="active">Dashboard</span>
</div>

<%=form_tag  root_path, method: :get, id: 'home_index_form' ,:class=>"basic-form no-padding"  do %>
	<div class="col-md-3 col-sm-3">
	   
	    <div class="input_box ">
	        <span class="select_lbl">Select Project</span>
			<span>
			 	<%= select_tag(:project_id, options_from_collection_for_select(Project.all.order(:id), :id, :name,params[:project_id]),class:"input_box_style", prompt: "all") %>
	        </span>
		</div>
	</div>
<%end%>	


<div class="index_list_page">
	<%= render "home_tasks_list"%>
</div>	

app/views/home/index.js.erb
$(".index_list_page").html("<%=escape_javascript(render("home_tasks_list"))%>");

app/views/layouts/_top_bar.html.erb
<div class="login_logout_details">
	<% if user_signed_in? %>
	  <span class="login_detail">Logged in as: <%=current_user.email%></span>
	  <%= link_to('Home', root_path)%> |
	  <%= link_to('Projects', projects_path)%> |
	  <%= link_to('Edit Profile', edit_user_registration_path)%> |
	  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>   
	<%end%>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeReportingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
	
  <body class="text_align_center sign_in_page">
  	
  	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
	
	<div class="top-bar">
		<%= render 'layouts/top_bar'%>
	</div>
	
	<div style="color: red;font-size: 12px;"><%=flash[:error]%></div>
	<div style="color: green;font-size: 12px;"><%=flash[:success]%></div>
    
	<%= yield %>
		
  </body>
</html>

app/views/projects/_action_buttons.html.erb
<td>
	<%=link_to edit_project_path(project.id) do%>
		<span class="fa fa-edit edit_icon"></span>
	<%end%>
</td>
<td>
	<%=link_to project_path(project.id), method: :delete do%>
		<span class="fa fa-trash delete_icon"></span>
	<%end%>
</td>
<td>
	<%=link_to tasks_path(project_id: project.id) do%>
		<span class="fa fa-search"></span>
	<%end%>
</td>	

app/views/projects/_book_details.html.erb
<div class="col-12 show_header">
	<span class="header_style">Header</span>
	<span class="close_window">X</span>
</div>
<div class="col-12">
	<div class="col-lg-4 left_sec" style="float: left;">
  		<span class="book_cover">
  			<%= (!@book.blank? && !@book.book_cover.blank?) ? image_tag(@book.book_cover_url) : image_tag("Silhouette.png")%>
  		</span>
	</div>
	<div class="col-lg-8 right_sec">
		<span class="details_sec">
			<span class="name">Book Name : </span>
			<span class="description"><%= @book.book_name %></span>
		</span>
		<span class="details_sec">
			<span class="name">Author : </span>
			<span class="description"><%= @book.author %></span>
		</span>
		<span class="details_sec">
			<span class="name">ISBN : </span>
			<span class="description"><%= @book.isbn %></span>
		</span>
		<span class="details_sec">
			<span class="name">Price : </span>
			<span class="description"><%= @book.price %></span>
		</span>
		<span class="details_sec">
			<span class="name">Category : </span>
			<span class="description"><%= @book.category %></span>
		</span>
	</div>
	
</div>

app/views/projects/_form.html.erb
<div class="form-style">
	<div class="page-form">
		<div class="row"><%= form.text_field :name, class: "form-control", placeholder: "Name(can't be blank)" %></div>
		<div class="row"><%= form.text_field :description, class: "form-control", placeholder: "Description" %></div>
		<div class="row">
			<%= form.submit "Submit", :class=>"btn btn-warning" %>
			<%=link_to projects_path do %><span class="btn btn-warning" style="margin-left: 10px;">Cancel</span><%end%>
		</div>
	</div>
</div>

app/views/projects/_proj_table_header.html.erb
<thead class="cf">
  <tr style="width:100%;">
  	<th>Name</th>
	<th>Description</th>
    <th>Edit</th>
	<th>Delete</th>
	<th>View Tasks</th>
  </tr>
</thead>

app/views/projects/_projects_list.html.erb
<table class="table table-bordered table-striped table-condensed cf">
    <%= render "projects/proj_table_header"%>
    <tbody>
        <%@projects.each_with_index do |project| %>
        <tr>
			<td>
				<%=project.name%>
			</td>
			<td>
				<%=project.description%>
			</td>
			<%= render "projects/action_buttons",project: project%>			
        </tr>
        <%end %>
    </tbody>
</table>

app/views/projects/_publish_status.html.erb
<% if book.publish_status %>
	<%=link_to publish_book_book_path(id: book.id, status: false), method: :patch, remote: true do%>
		<span class="status_false">Withhold</span>
	<%end%>
<%else%>
	<%=link_to publish_book_book_path(id: book.id, status: true), method: :patch, remote: true do%>
		<span class="status_true">Publish</span>
	<%end%>
<%end%>

app/views/projects/edit.html.erb
<div class="breadcrumbs breadcrumb_style">
	<span class="fa fa-home"></span> / Projects / <span class="active">Edit</span>
</div>
<div>
	<%= form_with model: @project do |form|%>
		<%= render "form", form: form%>
	<%end%>
</div>

app/views/projects/index.html.erb
<div class="breadcrumbs breadcrumb_style">
	<span class="fa fa-home"></span> /<span class="active">Projects</span>
</div>

<div class="nav">
	<%= link_to "Add Projects", new_project_path, :class => "btn rounded btn-primary"%>
</div>

<% if !@projects.blank? %>
	<div id="projects_list" style="width:100%;float: left;">
		<%= render "projects_list"%>
	</div>
<%else%>
	<div class="noRecords"><span class="fa fa-info-circle"></span> No Projects Found</div>
<%end%>

app/views/projects/new.html.erb
<div class="breadcrumbs breadcrumb_style">
	<span class="fa fa-home"></span> / Projects / <span class="active">New</span>
</div>
<div>
	<%= form_with model: @project do |form|%>
		<%= render "form", form: form%>
	<%end%>
</div>

app/views/projects/publish_book.js.erb
$('.book_<%=@book.id%>').html("<%=escape_javascript(render("publish_status", book: @book))%>");

app/views/projects/show.js.erb
$("#model_window_main_view").html("");
$("#model_window_main_view").html("<%=escape_javascript(render("book_details"))%>");
$("#model_window_main_view").show();
$(".light_box_wrapper").show();

app/views/projects/sort_books.js.erb
$("#books_list").html("<%=escape_javascript(render("books_list"))%>");
$(".sort_arrow").removeClass("<%=@arrow_class[0]%>")
$(".<%=params[:sort_obj]%>").find('.sort_arrow').addClass("<%=@arrow_class[1]%>")
$(".<%=params[:sort_obj]%>").data('sort-order',"<%=params[:sort_order]%>")

app/views/tasks/_action_buttons.html.erb
<td>
	<%=link_to edit_task_path(task.id) do%>
		<span class="fa fa-edit edit_icon"></span>
	<%end%>
</td>
<td>
	<%=link_to task_path(task.id), method: :delete do%>
		<span class="fa fa-trash delete_icon"></span>
	<%end%>
</td>

app/views/tasks/_book_details.html.erb
<div class="col-12 show_header">
	<span class="header_style">Header</span>
	<span class="close_window">X</span>
</div>
<div class="col-12">
	<div class="col-lg-4 left_sec" style="float: left;">
  		<span class="book_cover">
  			<%= (!@book.blank? && !@book.book_cover.blank?) ? image_tag(@book.book_cover_url) : image_tag("Silhouette.png")%>
  		</span>
	</div>
	<div class="col-lg-8 right_sec">
		<span class="details_sec">
			<span class="name">Book Name : </span>
			<span class="description"><%= @book.book_name %></span>
		</span>
		<span class="details_sec">
			<span class="name">Author : </span>
			<span class="description"><%= @book.author %></span>
		</span>
		<span class="details_sec">
			<span class="name">ISBN : </span>
			<span class="description"><%= @book.isbn %></span>
		</span>
		<span class="details_sec">
			<span class="name">Price : </span>
			<span class="description"><%= @book.price %></span>
		</span>
		<span class="details_sec">
			<span class="name">Category : </span>
			<span class="description"><%= @book.category %></span>
		</span>
	</div>
	
</div>

app/views/tasks/_form.html.erb
<div class="form-style">
	<div class="page-form">
		<div class="row"><%= form.text_field :name, class: "form-control", placeholder: "Name(can't be blank)" %></div>
		<div class="row"><%= form.text_field :description, class: "form-control", placeholder: "Description" %></div>
		<div class="row"><%= form.text_field :time_taken, class: "form-control", placeholder: "Time taken (in hours)" %></div>
		<div class="row"><%= form.text_field :date, class: "form-control",:id => "datepicker", placeholder: "Date",:value=> @task.date && @task.try(:date).strftime("%Y-%m-%d") %></div>
		<div class="row">
			Select Project
			<%= form.select(:project_id, options_from_collection_for_select(Project.all.order(:id), :id, :name,params[:project_id]),class:"input_box_style") %>
		</div>
		<div class="row">
			<%= form.submit "Submit", :class=>"btn btn-warning" %>
			<%=link_to tasks_path(project_id: @project.id) do %><span class="btn btn-warning" style="margin-left: 10px;">Cancel</span><%end%>
		</div>
	</div>
</div>

<script>
  $('#datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>	

app/views/tasks/_publish_status.html.erb
<% if book.publish_status %>
	<%=link_to publish_book_book_path(id: book.id, status: false), method: :patch, remote: true do%>
		<span class="status_false">Withhold</span>
	<%end%>
<%else%>
	<%=link_to publish_book_book_path(id: book.id, status: true), method: :patch, remote: true do%>
		<span class="status_true">Publish</span>
	<%end%>
<%end%>

app/views/tasks/_task_table_header.html.erb
<thead class="cf">
  <tr style="width:100%;">
    <th>Id</th>
  	<th>Name</th>
	<th>Description</th>
    <th>Time Taken(in hours)</th>
	<th>Date</th>
	<th>Edit</th>
	<th>Delete</th>
  </tr>
</thead>

app/views/tasks/_tasks_list.html.erb
<table class="table table-bordered table-striped table-condensed cf">
    <%= render "task_table_header"%>
    <tbody>
        <%@tasks.each_with_index do |task| %>
        <tr>
        	<td>
				<%=task.id%>
			</td>
			<td>
				<%=task.name%>
			</td>
			<td>
				<%=task.description%>
			</td>
			<td>
			   <%=task.time_taken%>
			</td>
			<td>
			   <%=task.date.strftime("%m-%d-%Y") if task.date%>
			</td>
			<%= render "action_buttons",task: task%>		
        </tr>
        <%end %>
    </tbody>
</table>
<%= will_paginate @tasks %>

app/views/tasks/edit.html.erb
<div class="breadcrumbs breadcrumb_style">
	<span class="fa fa-home"></span> / Project - <%=@project.name%> / <span class="active">Edit</span>
</div>
<div>
	<%= form_with model: @task do |form|%>
		<%= render "form", form: form%>
	<%end%>
</div>

app/views/tasks/index.html.erb
<div class="breadcrumbs breadcrumb_style">
	<span class="fa fa-home"></span> /Project- <%=@project.name%>/<span class="active">Tasks</span>
</div>

<div class="nav">
	<%= link_to "Add Tasks",new_task_path(project_id: @project.id), :class => "btn rounded btn-primary"%>
	<%= link_to "Excel", tasks_path(project_id: @project.id, format: "xlsx"),:class=>"btn rounded btn-primary xl_report" %>
</div>

<% if !@tasks.blank? %>
	<div id="projects_list" style="width:100%;float: left;">
		<%= render "tasks_list"%>
	</div>
<%else%>
	<div class="noRecords"><span class="fa fa-info-circle"></span> No Tasks Found</div>
<%end%>

app/views/tasks/new.html.erb
<div class="breadcrumbs breadcrumb_style">
	<span class="fa fa-home"></span> / Tasks / <span class="active">New</span>
</div>
<div>
	<%= form_with model: @task do |form|%>
		<%= render "form", form: form%>
	<%end%>
</div>

app/views/tasks/publish_book.js.erb
$('.book_<%=@book.id%>').html("<%=escape_javascript(render("publish_status", book: @book))%>");

app/views/tasks/show.js.erb
$("#model_window_main_view").html("");
$("#model_window_main_view").html("<%=escape_javascript(render("book_details"))%>");
$("#model_window_main_view").show();
$(".light_box_wrapper").show();

app/views/tasks/sort_books.js.erb
$("#books_list").html("<%=escape_javascript(render("books_list"))%>");
$(".sort_arrow").removeClass("<%=@arrow_class[0]%>")
$(".<%=params[:sort_obj]%>").find('.sort_arrow').addClass("<%=@arrow_class[1]%>")
$(".<%=params[:sort_obj]%>").data('sort-order',"<%=params[:sort_order]%>")